# Generated by Django 4.2 on 2023-08-03 12:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='Desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
