# Generated by Django 4.2 on 2023-08-07 08:51

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0002_alter_postblog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='Desc',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
